// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/6/2026, 10:52:09 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/asani/Development/sideproject/portfolio-management/portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/asani/Development/sideproject/portfolio-management/portfolio/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/asani/Development/sideproject/portfolio-management/portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/asani/Development/sideproject/portfolio-management/portfolio/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/asani/Development/sideproject/portfolio-management/portfolio/plugins/**/*.{js,ts,mjs}","/Users/asani/Development/sideproject/portfolio-management/portfolio/composables/**/*.{js,ts,mjs}","/Users/asani/Development/sideproject/portfolio-management/portfolio/utils/**/*.{js,ts,mjs}","/Users/asani/Development/sideproject/portfolio-management/portfolio/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/asani/Development/sideproject/portfolio-management/portfolio/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/asani/Development/sideproject/portfolio-management/portfolio/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/asani/Development/sideproject/portfolio-management/portfolio/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;