// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/4/2026, 4:22:01 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/asani/Downloads/portfolio-nuxt (1)/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/asani/Downloads/portfolio-nuxt (1)/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/asani/Downloads/portfolio-nuxt (1)/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/asani/Downloads/portfolio-nuxt (1)/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/asani/Downloads/portfolio-nuxt (1)/plugins/**/*.{js,ts,mjs}","/Users/asani/Downloads/portfolio-nuxt (1)/composables/**/*.{js,ts,mjs}","/Users/asani/Downloads/portfolio-nuxt (1)/utils/**/*.{js,ts,mjs}","/Users/asani/Downloads/portfolio-nuxt (1)/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/asani/Downloads/portfolio-nuxt (1)/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/asani/Downloads/portfolio-nuxt (1)/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/asani/Downloads/portfolio-nuxt (1)/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;